"""
=============================================================
MODEL 3 — Fusion (Acoustic + Linguistic) Parkinson's Detection
Disease  : Parkinson's Disease (PD)
Modality : Acoustic + Linguistic (fusion)
Dataset  : Spontaneous Dialogue — PD vs HC
Transcript: Whisper base.en (cached from Model 2)
Features : 144 combined (115 acoustic + 29 linguistic)
           MI selection keeps top 25
Model    : XGBoost
Selection: SelectKBest (Mutual Information, top 25)
Sampling : SMOTE (k=3)
CV       : Leave-One-Out (LOO-CV)
Results  : Accuracy 0.694 | Precision 0.625 | Recall 0.667
           F1 0.645 | ROC-AUC 0.756
=============================================================
Uses SpontaneousDialogue dataset only.
- Acoustic features extracted via librosa from the raw audio
- Linguistic features from Whisper base.en transcripts (cached)
- Both feature sets combined → MI selection → SMOTE → XGBoost
- LOO-CV for honest evaluation on small N
"""

import os
import re
import json
import warnings
import numpy as np
import pandas as pd
import librosa
import xgboost as xgb
import shap
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.model_selection import LeaveOneOut
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, classification_report,
    ConfusionMatrixDisplay, RocCurveDisplay,
)

warnings.filterwarnings("ignore")

BASE   = os.path.dirname(os.path.abspath(__file__))
PD_DIR = os.path.join(BASE, "Dataset", "SpontaneousDialogue(linguistic)", "PD")
HC_DIR = os.path.join(BASE, "Dataset", "SpontaneousDialogue(linguistic)", "HC")
OUT    = os.path.join(BASE, "results_fusion")
os.makedirs(OUT, exist_ok=True)

# Reuse transcripts already generated by model2
TRANSCRIPT_CACHE = os.path.join(BASE, "results_linguistic", "transcripts.csv")


# ══════════════════════════════════════════════════════════════════════════════
# ACOUSTIC FEATURE EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════
def extract_acoustic_features(path: str) -> dict:
    y, sr = librosa.load(path, sr=None, mono=True)
    y, _  = librosa.effects.trim(y, top_db=20)
    feats = {}

    # MFCCs (13) + delta + delta-delta
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    for i, (m, s) in enumerate(zip(mfcc.mean(axis=1), mfcc.std(axis=1)), 1):
        feats[f"ac_mfcc{i}_mean"] = m;  feats[f"ac_mfcc{i}_std"] = s

    d1 = librosa.feature.delta(mfcc)
    for i, (m, s) in enumerate(zip(d1.mean(axis=1), d1.std(axis=1)), 1):
        feats[f"ac_dmfcc{i}_mean"] = m;  feats[f"ac_dmfcc{i}_std"] = s

    d2 = librosa.feature.delta(mfcc, order=2)
    for i, (m, s) in enumerate(zip(d2.mean(axis=1), d2.std(axis=1)), 1):
        feats[f"ac_d2mfcc{i}_mean"] = m;  feats[f"ac_d2mfcc{i}_std"] = s

    # F0 / voicing
    f0, voiced, _ = librosa.pyin(y, fmin=50, fmax=500, sr=sr)
    f0v = f0[voiced] if voiced.any() else np.array([0.0])
    feats["ac_f0_mean"]         = float(np.mean(f0v))
    feats["ac_f0_std"]          = float(np.std(f0v))
    feats["ac_f0_range"]        = float(np.ptp(f0v))
    feats["ac_f0_jitter"]       = float(np.mean(np.abs(np.diff(f0v)))) if len(f0v) > 1 else 0.0
    feats["ac_voiced_fraction"] = float(voiced.mean())

    # RMS / shimmer
    rms = librosa.feature.rms(y=y)[0]
    feats["ac_rms_mean"]       = float(rms.mean())
    feats["ac_rms_std"]        = float(rms.std())
    feats["ac_shimmer_approx"] = float(np.mean(np.abs(np.diff(rms))) / (rms.mean() + 1e-9))

    # Spectral
    sc  = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
    sb  = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]
    sro = librosa.feature.spectral_rolloff(y=y, sr=sr)[0]
    sf  = librosa.feature.spectral_flatness(y=y)[0]
    sct = librosa.feature.spectral_contrast(y=y, sr=sr)
    feats["ac_spec_centroid_mean"]  = float(sc.mean());  feats["ac_spec_centroid_std"]  = float(sc.std())
    feats["ac_spec_bandwidth_mean"] = float(sb.mean());  feats["ac_spec_bandwidth_std"] = float(sb.std())
    feats["ac_spec_rolloff_mean"]   = float(sro.mean()); feats["ac_spec_rolloff_std"]   = float(sro.std())
    feats["ac_spec_flatness_mean"]  = float(sf.mean());  feats["ac_spec_flatness_std"]  = float(sf.std())
    for b in range(sct.shape[0]):
        feats[f"ac_spec_contrast_b{b+1}"] = float(sct[b].mean())

    # ZCR
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    feats["ac_zcr_mean"] = float(zcr.mean());  feats["ac_zcr_std"] = float(zcr.std())

    # Chroma
    chroma = librosa.feature.chroma_stft(y=y, sr=sr)
    feats["ac_chroma_mean"] = float(chroma.mean());  feats["ac_chroma_std"] = float(chroma.std())

    # Mel
    mel_db = librosa.power_to_db(librosa.feature.melspectrogram(y=y, sr=sr, n_mels=40), ref=np.max)
    feats["ac_mel_mean"] = float(mel_db.mean());  feats["ac_mel_std"] = float(mel_db.std())

    # Tonnetz
    y_h = librosa.effects.harmonic(y)
    ton = librosa.feature.tonnetz(y=y_h, sr=sr)
    for t in range(ton.shape[0]):
        feats[f"ac_tonnetz{t+1}"] = float(ton[t].mean())

    # Onset rate & pause ratio
    onsets   = librosa.onset.onset_detect(y=y, sr=sr, units="time")
    duration = librosa.get_duration(y=y, sr=sr)
    feats["ac_onset_rate"] = float(len(onsets) / max(duration, 1e-3))
    rms2 = librosa.feature.rms(y=y, hop_length=512)[0]
    feats["ac_pause_ratio"] = float((rms2 < rms2.max() * 0.02).mean())

    return feats


# ══════════════════════════════════════════════════════════════════════════════
# LINGUISTIC FEATURE EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════
FUNCTION_WORDS = {
    "the","a","an","is","are","was","were","be","been","being","have","has","had",
    "do","does","did","will","would","shall","should","may","might","must","can","could",
    "and","but","or","nor","so","yet","for","at","by","in","on","to","up","as","of",
    "if","then","than","that","this","these","those","it","its","i","you","he","she",
    "we","they","me","him","her","us","them","my","your","his","our","their","which",
    "who","what","when","where","how","with","from","into","through","during","not",
    "no","nor","both","either","neither","each","every","all","any","some","such",
}
FILLERS = {"uh","um","er","ah","like","okay","well","right","so"}


def tokenize(text: str) -> list:
    return re.findall(r"\b[a-z']+\b", text.lower())


def extract_linguistic_features(text: str, words_json: str) -> dict:
    feats     = {}
    tokens    = tokenize(text)
    sentences = [s.strip() for s in re.split(r"[.!?]+", text.strip()) if s.strip()]
    n_tokens  = len(tokens)
    n_chars   = len(text.replace(" ", ""))
    n_sent    = max(len(sentences), 1)
    vocab     = set(tokens)

    feats["li_ttr"]              = len(vocab) / max(n_tokens, 1)
    feats["li_vocab_size"]       = len(vocab)
    feats["li_word_count"]       = n_tokens

    wl = [len(t) for t in tokens]
    feats["li_avg_word_len"] = np.mean(wl) if wl else 0.0
    feats["li_std_word_len"] = np.std(wl)  if wl else 0.0

    sl = [len(tokenize(s)) for s in sentences]
    feats["li_avg_sent_len"] = np.mean(sl) if sl else 0.0
    feats["li_std_sent_len"] = np.std(sl)  if sl else 0.0
    feats["li_num_sentences"] = n_sent

    n_func = sum(1 for t in tokens if t in FUNCTION_WORDS)
    feats["li_func_word_ratio"]    = n_func / max(n_tokens, 1)
    feats["li_content_word_ratio"] = 1.0 - feats["li_func_word_ratio"]
    feats["li_lexical_density"]    = feats["li_content_word_ratio"]

    bigrams  = list(zip(tokens, tokens[1:]))
    trigrams = list(zip(tokens, tokens[1:], tokens[2:]))
    feats["li_bigram_rep"]  = (len(bigrams)  - len(set(bigrams)))  / max(len(bigrams),  1)
    feats["li_trigram_rep"] = (len(trigrams) - len(set(trigrams))) / max(len(trigrams), 1)
    feats["li_top_word_dom"]= (Counter(tokens).most_common(1)[0][1] / n_tokens) if tokens else 0.0

    n_fill = sum(1 for t in tokens if t in FILLERS)
    feats["li_filler_ratio"] = n_fill / max(n_tokens, 1)
    feats["li_filler_count"] = n_fill

    feats["li_punct_density"]       = sum(1 for c in text if c in ".,;:!?") / max(len(text), 1)
    feats["li_commas_per_sentence"] = text.count(",") / max(n_sent, 1)

    try:
        word_list = json.loads(words_json)
    except Exception:
        word_list = []

    if len(word_list) >= 2:
        durs        = [e - s for _, s, e in word_list]
        gaps        = [word_list[i+1][1] - word_list[i][2] for i in range(len(word_list)-1)]
        gaps_clean  = [g for g in gaps if g >= 0]
        total_sp    = sum(durs)
        total_time  = word_list[-1][2] - word_list[0][1]

        feats["li_avg_word_dur"]     = np.mean(durs)
        feats["li_std_word_dur"]     = np.std(durs)
        feats["li_avg_gap"]          = np.mean(gaps_clean) if gaps_clean else 0.0
        feats["li_std_gap"]          = np.std(gaps_clean)  if gaps_clean else 0.0
        feats["li_max_pause"]        = max(gaps_clean)     if gaps_clean else 0.0
        feats["li_long_pause_count"] = sum(1 for g in gaps_clean if g > 0.5)
        feats["li_long_pause_ratio"] = feats["li_long_pause_count"] / max(len(gaps_clean), 1)
        feats["li_speech_rate"]      = len(word_list) / max(total_time, 1e-3)
        feats["li_articu_rate"]      = len(word_list) / max(total_sp, 1e-3)
        feats["li_speaking_ratio"]   = total_sp / max(total_time, 1e-3)
        feats["li_chars_per_sec"]    = n_chars / max(total_time, 1e-3)
    else:
        for k in ["li_avg_word_dur","li_std_word_dur","li_avg_gap","li_std_gap",
                  "li_max_pause","li_long_pause_count","li_long_pause_ratio",
                  "li_speech_rate","li_articu_rate","li_speaking_ratio","li_chars_per_sec"]:
            feats[k] = 0.0

    return feats


# ══════════════════════════════════════════════════════════════════════════════
# BUILD COMBINED DATASET
# ══════════════════════════════════════════════════════════════════════════════
ACOU_CACHE = os.path.join(OUT, "fusion_acoustic_features.csv")

# --- Acoustic features ---
if os.path.exists(ACOU_CACHE):
    print("Loading cached acoustic features (SpontaneousDialogue) …")
    acou_df = pd.read_csv(ACOU_CACHE)
else:
    print("Extracting acoustic features from SpontaneousDialogue …")
    records = []
    for label, folder in [(1, PD_DIR), (0, HC_DIR)]:
        for fname in sorted(os.listdir(folder)):
            if not fname.lower().endswith(".wav"):
                continue
            path = os.path.join(folder, fname)
            try:
                f = extract_acoustic_features(path)
                f["label"] = label;  f["file"] = fname
                records.append(f)
                print(f"  {'PD' if label else 'HC'} {fname}")
            except Exception as e:
                print(f"  ERROR {fname}: {e}")
    acou_df = pd.DataFrame(records)
    acou_df.to_csv(ACOU_CACHE, index=False)

# --- Linguistic features (from cached transcripts) ---
print("\nLoading transcripts and extracting linguistic features …")
if not os.path.exists(TRANSCRIPT_CACHE):
    raise FileNotFoundError(
        f"Transcript cache not found at {TRANSCRIPT_CACHE}. Run model2_linguistic.py first."
    )
trans_df = pd.read_csv(TRANSCRIPT_CACHE)

ling_records = []
for _, row in trans_df.iterrows():
    f = extract_linguistic_features(row["text"], row["words_json"])
    f["file"] = row["file"]
    ling_records.append(f)
ling_df = pd.DataFrame(ling_records)

# --- Merge on filename ---
merged = acou_df.merge(ling_df, on="file")
print(f"\nFusion dataset: {len(merged)} samples | {merged['label'].sum()} PD / {(merged['label']==0).sum()} HC")

acou_cols = [c for c in acou_df.columns if c not in ("label", "file")]
ling_cols = [c for c in ling_df.columns if c != "file"]
all_feat_cols = acou_cols + ling_cols
print(f"Acoustic features : {len(acou_cols)}")
print(f"Linguistic features: {len(ling_cols)}")
print(f"Total combined     : {len(all_feat_cols)}")

X        = merged[all_feat_cols].values.astype(float)
y_labels = merged["label"].values

# Tag each feature with its modality (for analysis later)
feature_modality = {f: "Acoustic" for f in acou_cols}
feature_modality.update({f: "Linguistic" for f in ling_cols})


# ══════════════════════════════════════════════════════════════════════════════
# PIPELINE: Scale → MI Selection → SMOTE → XGBoost
# ══════════════════════════════════════════════════════════════════════════════
N_FEATURES = 25   # keep top-25 from combined pool

clf = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    eval_metric="logloss",
    random_state=42,
)

pipe = ImbPipeline([
    ("scaler", StandardScaler()),
    ("select", SelectKBest(mutual_info_classif, k=N_FEATURES)),
    ("smote",  SMOTE(random_state=42, k_neighbors=3)),
    ("clf",    clf),
])


# ══════════════════════════════════════════════════════════════════════════════
# LEAVE-ONE-OUT CV
# ══════════════════════════════════════════════════════════════════════════════
print("\nRunning Leave-One-Out CV …")
loo         = LeaveOneOut()
y_pred_loo  = []
y_proba_loo = []

for train_idx, test_idx in loo.split(X):
    X_tr, X_te = X[train_idx], X[test_idx]
    y_tr        = y_labels[train_idx]
    pipe.fit(X_tr, y_tr)
    y_pred_loo.append(pipe.predict(X_te)[0])
    y_proba_loo.append(pipe.predict_proba(X_te)[0, 1])

y_pred_loo  = np.array(y_pred_loo)
y_proba_loo = np.array(y_proba_loo)

print("\n── LOO-CV Results ──")
acc  = accuracy_score(y_labels, y_pred_loo)
prec = precision_score(y_labels, y_pred_loo, zero_division=0)
rec  = recall_score(y_labels, y_pred_loo, zero_division=0)
f1   = f1_score(y_labels, y_pred_loo, zero_division=0)
auc  = roc_auc_score(y_labels, y_proba_loo)

print(f"  Accuracy : {acc:.4f}")
print(f"  Precision: {prec:.4f}")
print(f"  Recall   : {rec:.4f}")
print(f"  F1-Score : {f1:.4f}")
print(f"  ROC-AUC  : {auc:.4f}")
print()
print(classification_report(y_labels, y_pred_loo, target_names=["HC", "PD"]))

pd.DataFrame([{"Metric": m, "Value": v} for m, v in [
    ("Accuracy",acc),("Precision",prec),("Recall",rec),("F1",f1),("ROC-AUC",auc)
]]).to_csv(os.path.join(OUT, "loo_metrics.csv"), index=False)


# ══════════════════════════════════════════════════════════════════════════════
# PLOTS: Confusion Matrix & ROC
# ══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
ConfusionMatrixDisplay(
    confusion_matrix(y_labels, y_pred_loo), display_labels=["HC","PD"]
).plot(ax=axes[0], colorbar=False)
axes[0].set_title("Fusion Model — LOO Confusion Matrix")
RocCurveDisplay.from_predictions(
    y_labels, y_proba_loo, ax=axes[1], name="XGBoost Fusion (LOO)"
)
axes[1].set_title(f"Fusion Model — ROC Curve (AUC={auc:.3f})")
plt.tight_layout()
plt.savefig(os.path.join(OUT, "confusion_roc.png"), dpi=150)
plt.close()


# ══════════════════════════════════════════════════════════════════════════════
# FINAL MODEL FOR INTERPRETABILITY
# ══════════════════════════════════════════════════════════════════════════════
print("\nFitting final model on full data …")
pipe.fit(X, y_labels)

scaler_full = pipe.named_steps["scaler"]
select_full = pipe.named_steps["select"]
clf_full    = pipe.named_steps["clf"]
sel_mask    = select_full.get_support()
sel_feats   = [f for f, m in zip(all_feat_cols, sel_mask) if m]
X_sel       = select_full.transform(scaler_full.transform(X))

# Feature importance coloured by modality
imp_df = pd.DataFrame({
    "feature":    sel_feats,
    "importance": clf_full.feature_importances_,
    "modality":   [feature_modality[f] for f in sel_feats],
})
imp_df = imp_df.sort_values("importance", ascending=False).reset_index(drop=True)
imp_df.to_csv(os.path.join(OUT, "feature_importance.csv"), index=False)

palette = {"Acoustic": "#2196F3", "Linguistic": "#FF5722"}
fig, ax = plt.subplots(figsize=(11, 8))
bars = sns.barplot(
    data=imp_df, y="feature", x="importance",
    hue="modality", dodge=False, palette=palette, ax=ax
)
ax.set_title(f"Fusion Model — Top {N_FEATURES} Feature Importances\n(blue = Acoustic, orange = Linguistic)")
ax.set_xlabel("XGBoost Importance")
ax.legend(title="Modality")
plt.tight_layout()
plt.savefig(os.path.join(OUT, "feature_importance.png"), dpi=150)
plt.close()

print(f"\nTop 15 features (with modality):\n{imp_df.head(15).to_string(index=False)}")

# Modality breakdown of selected features
modal_counts = imp_df["modality"].value_counts()
print(f"\nSelected feature breakdown: {dict(modal_counts)}")
total_imp_by_modal = imp_df.groupby("modality")["importance"].sum()
print(f"Total importance by modality:\n{total_imp_by_modal.to_string()}")

# Pie chart of modality contribution
fig, ax = plt.subplots(figsize=(6, 6))
ax.pie(
    total_imp_by_modal.values,
    labels=total_imp_by_modal.index,
    autopct="%1.1f%%",
    colors=[palette[m] for m in total_imp_by_modal.index],
    startangle=90,
)
ax.set_title("Fusion Model — Feature Importance by Modality")
plt.tight_layout()
plt.savefig(os.path.join(OUT, "modality_importance_pie.png"), dpi=150)
plt.close()


# ══════════════════════════════════════════════════════════════════════════════
# SHAP ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════
print("\nRunning SHAP analysis …")
X_sel_df  = pd.DataFrame(X_sel, columns=sel_feats)
explainer = shap.TreeExplainer(clf_full)
shap_vals = explainer.shap_values(X_sel_df)

# Beeswarm — colour dots by modality isn't native in shap, but we annotate the y-axis
plt.figure(figsize=(11, 9))
shap.summary_plot(shap_vals, X_sel_df, show=False, max_display=25)
plt.title("Fusion Model — SHAP Summary (Beeswarm)")
plt.tight_layout()
plt.savefig(os.path.join(OUT, "shap_summary.png"), dpi=150, bbox_inches="tight")
plt.close()

plt.figure(figsize=(11, 8))
shap.summary_plot(shap_vals, X_sel_df, plot_type="bar", show=False, max_display=25)
plt.title("Fusion Model — SHAP Feature Importance (Bar)")
plt.tight_layout()
plt.savefig(os.path.join(OUT, "shap_bar.png"), dpi=150, bbox_inches="tight")
plt.close()

pd.DataFrame(shap_vals, columns=sel_feats).assign(
    file=merged["file"].values, label=merged["label"].values
).to_csv(os.path.join(OUT, "shap_values.csv"), index=False)


# ══════════════════════════════════════════════════════════════════════════════
# SUMMARY COMPARISON TABLE
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*55)
print("  FINAL COMPARISON (all on SpontaneousDialogue, LOO-CV)")
print("="*55)
print(f"  {'Metric':<12} {'Acoustic-only':>14} {'Linguistic-only':>16} {'FUSION':>8}")
print("-"*55)

# Load previously saved metrics for acoustic-only and linguistic-only on same data
# (we ran those on the same dialogue dataset in model2; acoustic-only was on ReadText)
# We'll note that ReadText acoustic != Dialogue acoustic, so we report what we have:
rows = [
    ("Accuracy",  "—",      "0.528",  f"{acc:.3f}"),
    ("Precision", "—",      "0.417",  f"{prec:.3f}"),
    ("Recall",    "—",      "0.333",  f"{rec:.3f}"),
    ("F1-Score",  "—",      "0.370",  f"{f1:.3f}"),
    ("ROC-AUC",   "—",      "0.568",  f"{auc:.3f}"),
]
for r in rows:
    print(f"  {r[0]:<12} {r[1]:>14} {r[2]:>16} {r[3]:>8}")
print("="*55)
print("  (Acoustic-only on SpontaneousDialogue not previously run)")
print(f"\nAll results saved to: {OUT}")
print("Done.")
